services:
    ProcessManagerBundle\Command\CleanupProcessDataCommand:
        arguments:
            - '@ProcessManagerBundle\Service\CleanupService'
            - '%process_manager.log_directory%'
        tags:
            - { name: 'console.command', command: 'process-manager:cleanup-process-data' }
